Repository AY2324S1-CS2113-T18-1/tp, pull requests merged in 2023-11, with the labels that each got.

#90 Modify getAvailableCoordinatesString()
  src/main/java/chessmaster/pieces/ChessPiece.java
  src/main/java/chessmaster/pieces/King.java
Labels: enhancement

#98 Show board with previous move
  src/main/java/chessmaster/commands/ShowMovesCommand.java
  src/main/java/chessmaster/game/ChessTile.java
  src/main/java/chessmaster/game/Game.java
  src/main/java/chessmaster/ui/TextUI.java
  src/main/java/chessmaster/user/CPU.java
Labels: enhancement

#100 User guide first draft template
  docs/README.md
  docs/UserGuide.md
Labels: documentation

#103 Update MiniMax UML Sequence Diagram
  docs/diagrams/MiniMaxSequence.puml
  docs/images/MiniMaxSequenceDiagram.png
Labels: documentation

#104 Add ViewLegendCommand
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/StorageClass.puml
  docs/diagrams/StorageSequence.puml
  docs/images/StorageClass.png
  docs/images/StorageSequence.png
  src/main/java/chessmaster/commands/HelpCommand.java
  src/main/java/chessmaster/commands/LegendCommand.java
  src/main/java/chessmaster/commands/RulesCommand.java
  src/main/java/chessmaster/game/Game.java
  src/main/java/chessmaster/parser/Parser.java
  src/main/java/chessmaster/storage/Storage.java
Labels: enhancement

#114 Store `hasMoved` flag for each ChessPiece
  docs/UserGuide.md
  src/main/java/chessmaster/ChessMaster.java
  src/main/java/chessmaster/game/ChessTile.java
  src/main/java/chessmaster/game/Game.java
  src/main/java/chessmaster/parser/Parser.java
  src/main/java/chessmaster/pieces/EmptyPiece.java
  src/main/java/chessmaster/storage/Storage.java
  src/main/java/chessmaster/ui/ExceptionMessages.java
  src/main/java/chessmaster/ui/TextUI.java
  src/main/java/chessmaster/ui/UiMessages.java
  src/test/java/chessmaster/parser/ParsePlayerColorTest.java
Labels: bug

#115 Start bug fix
  src/main/java/chessmaster/ChessMaster.java
  src/main/java/chessmaster/storage/Storage.java
  src/main/java/chessmaster/ui/UiMessages.java
  src/test/java/chessmaster/game/MiniMaxTest.java
Labels: bug

#149 Fix minimax aggro
  src/main/java/chessmaster/game/MiniMax.java
Labels: bug, enhancement

#152 Fix User Guide formatting
  docs/UserGuide.md
Labels: bug, documentation

#151 Fix wrong color when player loses
  src/main/java/chessmaster/game/Game.java
  src/main/java/chessmaster/ui/TextUI.java
Labels: bug

#150 Fix empty payload in moves command
  src/main/java/chessmaster/commands/ShowMovesCommand.java
  src/main/java/chessmaster/parser/Parser.java
  src/main/java/chessmaster/pieces/ChessPiece.java
Labels: bug

#154 Add invalid command
  src/main/java/chessmaster/commands/InvalidCommand.java
  src/main/java/chessmaster/commands/MoveCommand.java
  src/main/java/chessmaster/commands/ShowMovesCommand.java
  src/main/java/chessmaster/exceptions/NullPieceException.java
  src/main/java/chessmaster/parser/Parser.java
  src/main/java/chessmaster/ui/ExceptionMessages.java
Labels: bug

#153 Fix minor UI and UX bugs in `ChessMaster` class
  src/main/java/chessmaster/ChessMaster.java
  src/main/java/chessmaster/game/Game.java
  src/main/java/chessmaster/ui/TextUI.java
  src/main/java/chessmaster/ui/UiMessages.java
  src/main/java/chessmaster/user/Human.java
Labels: bug

#156 Add En Passant and new Check function
  src/main/java/chessmaster/game/ChessBoard.java
  src/main/java/chessmaster/game/Move.java
  src/main/java/chessmaster/pieces/ChessPiece.java
  src/main/java/chessmaster/pieces/EmptyPiece.java
  src/main/java/chessmaster/pieces/Pawn.java
Labels: bug, enhancement

#181 2.1 updates
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/MiniMaxSequence.puml
  docs/diagrams/MoveClass.puml
  docs/images/MiniMaxSequenceDiagram.png
  docs/images/MoveClass.png
  docs/team/onx001.md
  src/main/java/chessmaster/game/ChessBoard.java
  src/main/java/chessmaster/game/Color.java
  src/main/java/chessmaster/game/Game.java
  src/main/java/chessmaster/game/MiniMax.java
  src/main/java/chessmaster/ui/TextUI.java
  src/main/java/chessmaster/ui/UiMessages.java
Labels: bug

#196 Ignore empty spaces in each `nextLine` method in `Storage` class
  docs/UserGuide.md
  src/main/java/chessmaster/game/Game.java
  src/main/java/chessmaster/storage/Storage.java
  src/main/java/chessmaster/ui/UiMessages.java
  src/main/java/chessmaster/user/Player.java
Labels: bug
