Repository AY2324S1-CS2113-T18-1/tp, pull requests merged in 2023-10, with the labels that each got.

#53 Branch more OOP
  src/main/java/chessmaster/ChessMaster.java
  src/main/java/chessmaster/commands/AbortCommand.java
  src/main/java/chessmaster/commands/Command.java
  src/main/java/chessmaster/commands/CommandResult.java
  src/main/java/chessmaster/commands/HelpCommand.java
  src/main/java/chessmaster/commands/MoveCommand.java
  src/main/java/chessmaster/exceptions/ExceptionMessages.java
  src/main/java/chessmaster/exceptions/MoveOpponentPieceException.java
  src/main/java/chessmaster/exceptions/ParseColorException.java
  src/main/java/chessmaster/game/ChessBoard.java
  src/main/java/chessmaster/game/ChessTile.java
  src/main/java/chessmaster/game/Coordinate.java
  src/main/java/chessmaster/game/Game.java
  src/main/java/chessmaster/game/Move.java
  src/main/java/chessmaster/parser/Parser.java
  src/main/java/chessmaster/pieces/Bishop.java
  src/main/java/chessmaster/pieces/ChessPiece.java
  src/main/java/chessmaster/pieces/EmptyPiece.java
  src/main/java/chessmaster/pieces/King.java
  src/main/java/chessmaster/pieces/Knight.java
  src/main/java/chessmaster/pieces/Pawn.java
  src/main/java/chessmaster/pieces/Queen.java
  src/main/java/chessmaster/pieces/Rook.java
  src/main/java/chessmaster/storage/Storage.java
  src/main/java/chessmaster/ui/TextUI.java
  src/main/java/chessmaster/user/CPU.java
  src/main/java/chessmaster/user/Human.java
  src/main/java/chessmaster/user/Player.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: enhancement

#79 Implement board points and fix style checks
  docs/DeveloperGuide.md
  src/main/java/chessmaster/commands/ShowMovesCommand.java
  src/main/java/chessmaster/game/ChessBoard.java
  src/main/java/chessmaster/game/MiniMax.java
  src/main/java/chessmaster/game/Move.java
  src/main/java/chessmaster/pieces/Bishop.java
  src/main/java/chessmaster/pieces/ChessPiece.java
  src/main/java/chessmaster/pieces/EmptyPiece.java
  src/main/java/chessmaster/pieces/King.java
  src/main/java/chessmaster/pieces/Knight.java
  src/main/java/chessmaster/pieces/Pawn.java
  src/main/java/chessmaster/pieces/Queen.java
  src/main/java/chessmaster/pieces/Rook.java
  src/main/java/chessmaster/user/CPU.java
  src/test/java/chessmaster/chessboard/ChessBoardTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: bug, documentation, enhancement

#85 Add documentation for `Parser` and `Command`
  docs/DeveloperGuide.md
  docs/diagrams/ParseCommandSequence.png
  docs/diagrams/ParseCommandSequence.puml
  docs/diagrams/ParserCommandDiagram.png
  docs/diagrams/ParserCommandDiagram.puml
Labels: documentation

#87 Add documentation for `ChessMaster` and `Game`
  docs/DeveloperGuide.md
  docs/diagrams/ChessMasterSequence.puml
  docs/diagrams/GameSequence.puml
  docs/diagrams/OverallArchitecture.puml
  docs/images/ChessMasterSequence.png
  docs/images/GameSequence.png
  docs/images/OverallArchitecture.png
  docs/images/ParseCommandSequence.png
  docs/images/ParserCommandDiagram.png
Labels: documentation

#86 Add Documentation for Storage
  docs/DeveloperGuide.md
  docs/StorageClass.png
  docs/StorageClass.puml
  docs/StorageSequence.png
  docs/StorageSequence.puml
  docs/team/johndoe.md
Labels: documentation

#88 Update individual code contribution with repo sense @@author tags
  src/main/java/chessmaster/ChessMaster.java
  src/main/java/chessmaster/commands/AbortCommand.java
  src/main/java/chessmaster/commands/Command.java
  src/main/java/chessmaster/commands/CommandResult.java
  src/main/java/chessmaster/commands/HelpCommand.java
  src/main/java/chessmaster/commands/MoveCommand.java
  src/main/java/chessmaster/commands/RulesCommand.java
  src/main/java/chessmaster/commands/ShowCommand.java
  src/main/java/chessmaster/commands/ShowMovesCommand.java
  src/main/java/chessmaster/game/ChessBoard.java
  src/main/java/chessmaster/game/ChessTile.java
  src/main/java/chessmaster/game/Color.java
  src/main/java/chessmaster/game/Coordinate.java
  src/main/java/chessmaster/game/Game.java
  src/main/java/chessmaster/game/MiniMax.java
  src/main/java/chessmaster/game/Move.java
  src/main/java/chessmaster/parser/Parser.java
  src/main/java/chessmaster/pieces/ChessPiece.java
  src/main/java/chessmaster/pieces/EmptyPiece.java
  src/main/java/chessmaster/storage/Storage.java
  src/main/java/chessmaster/user/CPU.java
Labels: help wanted

#91 Add help message at start
  src/main/java/chessmaster/commands/HelpCommand.java
  src/main/java/chessmaster/game/Game.java
  text-ui-test/EXPECTED.TXT
Labels: enhancement

#92 Branch fix move validity
  src/main/java/chessmaster/commands/MoveCommand.java
  src/main/java/chessmaster/game/ChessBoard.java
  src/main/java/chessmaster/game/Move.java
Labels: enhancement

#94 Make `TextUI` methods non-static
  config/checkstyle/checkstyle.xml
  src/main/java/chessmaster/ChessMaster.java
  src/main/java/chessmaster/commands/AbortCommand.java
  src/main/java/chessmaster/commands/Command.java
  src/main/java/chessmaster/commands/HelpCommand.java
  src/main/java/chessmaster/commands/MoveCommand.java
  src/main/java/chessmaster/commands/RulesCommand.java
  src/main/java/chessmaster/commands/ShowCommand.java
  src/main/java/chessmaster/commands/ShowMovesCommand.java
  src/main/java/chessmaster/exceptions/ChessMasterException.java
  src/main/java/chessmaster/exceptions/InvalidMoveException.java
  src/main/java/chessmaster/exceptions/LoadBoardException.java
  src/main/java/chessmaster/exceptions/MoveOpponentPieceException.java
  src/main/java/chessmaster/exceptions/NullPieceException.java
  src/main/java/chessmaster/exceptions/ParseChessPieceException.java
  src/main/java/chessmaster/exceptions/ParseColorException.java
  src/main/java/chessmaster/exceptions/ParseCoordinateException.java
  src/main/java/chessmaster/exceptions/SaveBoardException.java
  src/main/java/chessmaster/game/BoardScoreTuple.java
  src/main/java/chessmaster/game/ChessBoard.java
  src/main/java/chessmaster/game/ChessTile.java
  src/main/java/chessmaster/game/Game.java
  src/main/java/chessmaster/game/MiniMax.java
  src/main/java/chessmaster/pieces/ChessPiece.java
  src/main/java/chessmaster/pieces/EmptyPiece.java
  src/main/java/chessmaster/ui/ExceptionMessages.java
  src/main/java/chessmaster/ui/TextUI.java
  src/main/java/chessmaster/user/Human.java
  src/test/java/chessmaster/game/ChessBoardTest.java
  src/test/java/chessmaster/parser/ParserTest.java
Labels: enhancement
